In [20]:
import pandas
import numpy
import glob
import csv

In [15]:
import pydatastream
from pydatastream import Datastream
import os

credentials = {}
with open('credentials.txt', 'r') as credentials_file:
  line = credentials_file.readline().split(',')
  credentials['username'] = line[0]
  credentials['password'] = line[1]

DWE = Datastream(username=credentials['username'], password=credentials['password'])
DWE.raise_on_error = False

DATATYPES = ['P', 'MV', 'PE', 'VA', 'VO', 'PTBV', 'MTBV']
INACTIVE_DATE = ['WC07015']

In [25]:
shanghai_equities_symbols = []

with open('shanghai-equities-rmb.csv', 'r') as shanghai_equities_csv:
    reader = csv.DictReader(shanghai_equities_csv)
    shanghai_equities_symbols = [line['Symbol'] for line in reader]

shanghai_equities_inactive_dates = DWE.fetch(shanghai_equities_symbols, INACTIVE_DATE, static=True)

In [47]:
shanghai_equities_inactive_dates[shanghai_equities_inactive_dates['WC07015'] != 'NA']

     CCY  SYMBOL              WC07015
1099  NA  CN:ACG  2004-09-15 00:00:00
1101  NA  CN:BAC  2007-12-26 00:00:00
1102  NA  CN:NEH  2004-09-22 00:00:00
1103  NA  CN:CXV  2010-01-05 00:00:00
1104  NA  CN:CNR  2015-05-21 00:00:00
1105  NA  CN:CKG  2015-05-26 00:00:00
1106  NA  CN:CSI  2005-09-16 00:00:00
1107  NA  CN:DAL  2004-09-15 00:00:00
1108  NA  CN:DLP  2007-12-13 00:00:00
1109  NA  CN:DBO  2008-02-19 00:00:00
1110  NA  CN:FUJ  2006-03-23 00:00:00
1111  NA  CN:HCM  2012-03-20 00:00:00
1112  NA  CN:SIC  2005-08-05 00:00:00
1113  NA  CN:HAC  2005-09-22 00:00:00
1114  NA  CN:HIS  2010-01-05 00:00:00
1115  NA  CN:HTA  2011-02-18 00:00:00
1116  NA  CN:HAH  2005-12-31 00:00:00
1117  NA  CN:HNP  2013-07-15 00:00:00
1119  NA  CN:NGC  2007-05-28 00:00:00
1120  NA  CN:HNN  2009-03-02 00:00:00
1121  NA  CN:YST  2007-06-04 00:00:00
1122  NA  CN:LAI  2012-02-28 00:00:00
1123  NA  CN:LZA  2007-04-30 00:00:00
1124  NA  CN:NWT  2014-06-05 00:00:00
1125  NA  CN:NEC  2010-02-26 00:00:00
1126  NA  CN:PET  2006-09-01 00:00:00
1128  NA  CN:SXB  2005-09-20 00:00:00
1129  NA  CN:SPA  2006-09-01 00:00:00
1130  NA  CN:ASH  2010-01-25 00:00:00
1131  NA  CN:SCJ  2003-09-22 00:00:00
...   ..     ...                  ...
1136  NA  CN:SZP  2010-02-12 00:00:00
1137  NA  CN:SAD  2007-04-30 00:00:00
1138  NA  CN:SDS  2011-08-23 00:00:00
1140  NA  CN:SEA  2008-12-16 00:00:00
1141  NA  CN:QPC  2006-04-21 00:00:00
1142  NA  CN:DMD  2005-03-25 00:00:00
1143  NA  CN:SXD  2009-08-31 00:00:00
1144  NA  CN:XNL  2005-09-21 00:00:00
1147  NA  30165K  2004-11-18 00:00:00
1151  NA  CN:SZR  2006-03-24 00:00:00
1158  NA  28027T  2002-10-08 00:00:00
1172  NA  86751V  2016-04-11 00:00:00
1178  NA  67770H  2011-08-19 00:00:00
1189  NA  8749Y6  2015-08-11 00:00:00
1197  NA  87071D  2011-01-19 00:00:00
1199  NA  86967C  2011-09-16 00:00:00
1211  NA  68159T  2015-11-23 00:00:00
1212  NA  27612M  2014-07-11 00:00:00
1236  NA  27612E  2015-11-23 00:00:00
1268  NA  86981F  2015-11-19 00:00:00
1269  NA  68143E  2015-11-19 00:00:00
1282  NA  41667T  2006-10-20 00:00:00
1283  NA  CN:SSU  2003-02-21 00:00:00
1291  NA  CN:SBX  2009-12-04 00:00:00
1293  NA  CN:SGR  2005-09-22 00:00:00
1296  NA  27609F  2005-05-11 00:00:00
1322  NA  51680T  2007-12-21 00:00:00
1327  NA  27612K  2013-11-15 00:00:00
1328  NA  8708NT  2013-11-12 00:00:00
1330  NA  27613D  2012-02-14 00:00:00

[64 rows x 3 columns]